export const TranslateBase: {[key: string]: string} = {
    "affenpinscher": "Pinczer małpi",
    "african": "Likaon pstry",
    "airedale": "Airedale terrier",
    "akita": "Akita",
    "appenzeller": "Appenzeller",
    "australian-shepherd": "Owczarek australijski",
    "basenji": "Basenji",
    "beagle": "Beagle",
    "bluetick": "Bluetick",
    "borzoi": "Borzoj",
    "bouvier": "Bouvier",
    "boxer": "Boxer",
    "brabancon": "Brabantczyk",
    "briard": "Owczarek francuski",
    "buhund-norwegian": "Buhund norweski",
    "bulldog-boston": "Buldog bostoński",
    "bulldog-english": "Buldog angielski",
    "bulldog-french": "Buldog francuski",
    "bullterrier-staffordshire": "staffik",
    "cattledog-australian": "Cattle dog australijski",
    "chihuahua": "chichuhaha",
    "chow": "Chow",
    "clumber": "Clumber spaniel",
    "cockapoo": "Cockapoo",
    "collie-border": "Border collie",
    "coonhound": "Coonhound",
    "corgi-cardigan": "Corgi cardigan",
    "cotondetulear": "Coton de Tulear",
    "dachshund": "Jamnik",
    "dalmatian": "Dalmatyńczyk",
    "dane-great": "Dog niemiecki",
    "deerhound-scottish": "Chart szkocki",
    "dhole": "dhole",
    "dingo": "Dingo australijski",
    "doberman": "Doberman",
    "elkhound-norwegian": "Elkhund szary",
    "entlebucher": "Entlebucher",
    "eskimo": "Pies eskimoski",
    "finnish-lapphund": "Fiński lapphund",
    "frise-bichon": "Bichon frise",
    "germanshepherd": "Owczarek niemiecki",
    "greyhound-italian": "Charcik włoski",
    "groenendael": "groenendael",
    "havanese": "hawańczyk",
    "hound-afghan": "ogar afgański",
    "hound-basset": "ogar basset",
    "hound-blood": "ogar gończy",
    "hound-english": "ogar angielski",
    "hound-ibizan": "ogar ibizan",
    "hound-plott": "hound plott",
    "hound-walker": "hound walker",
    "husky": "husky",
    "keeshond": "szpic szlachetny",
    "kelpie": "owczarek australijski",
    "komondor": "owczarek węgierski",
    "kuvasz": "kuvasz",
    "labradoodle": "labradoodle",
    "labrador": "labrador",
    "leonberg": "leonberg",
    "lhasa": "lhasa",
    "malamute": "malamute",
    "malinois": "owczarek belgijski malinos",
    "maltese": "maltańczyk",
    "mastiff-bull": "mastif byk",
    "mastiff-english": "mastiff angielski",
    "mastiff-tibetan": "mastif tybetański",
    "mexicanhairless": "meksykański bezwłosy",
    "mix": "kundel",
    "mountain-bernese": "berneński pies pasterski",
    "mountain-swiss": "szwajarski pies pasterski",
    "newfoundland": "newfoundland",
    "otterhound": "otterhound",
    "ovcharka-caucasian": "owczarek kaukaski",
    "papillon": "papillon",
    "pekinese": "pekińczyk",
    "pembroke": "pembroke",
    "pinscher-miniature": "pinczer miniaturowy",
    "pitbull": "pitbull",
    "pointer-german": "pointer niemicki",
    "pointer-germanlonghair": "pointer-niemiecki długowłosy",
    "pomeranian": "pomeranian",
    "poodle-miniature": "pudel miniaturowy",
    "poodle-standard": "pudel standard",
    "poodle-toy": "pudel toy",
    "pug": "mops",
    "puggle": "puggle",
    "pyrenees": "pirenejski pies górski",
    "redbone": "redbone",
    "retriever-chesapeake": "retriever chesapeake",
    "retriever-curly": "retriever kędzierzawy",
    "retriever-flatcoated": "retriever flatcoated",
    "retriever-golden": "golden retriever",
    "ridgeback-rhodesian": "ridgeback rhodesian",
    "rottweiler": "rottweiler",
    "saluki": "chart perski",
    "samoyed": "samoyed",
    "schipperke": "schipperke",
    "schnauzer-giant": "schnauzer olbrzym",
    "schnauzer-miniature": "schnauzer miniaturowy",
    "setter-english": "setter english",
    "setter-gordon": "setter gordon",
    "setter-irish": "setter irish",
    "sheepdog-english": "owczarek staroangielski",
    "sheepdog-shetland": "owczarek szetlandzki",
    "shiba": "shiba",
    "shihtzu": "shihtzu",
    "spaniel-blenheim": "spaniel blenheim",
    "spaniel-brittany": "spaniel brittany",
    "spaniel-cocker": "cocker spaniel angielski",
    "spaniel-irish": "islandzki spaniel wodny",
    "spaniel-japanese": "spaniel japoński",
    "spaniel-sussex": "spaniel sussex",
    "spaniel-welsh": "springer spaniel walijski",
    "springer-english": "springer spaniel angielski",
    "stbernard": "st bernard",
    "terrier-american": "terier amerykański",
    "terrier-australian": "terier australijski",
    "terrier-bedlington": "terrier bedlington",
    "terrier-border": "terrier border",
    "terrier-cairn": "terrier cairn",
    "terrier-dandie": "terrier dandie",
    "terrier-fox": "foksterier",
    "terrier-irish": "terier islandzki",
    "terrier-kerryblue": "terrier kerryblue",
    "terrier-lakeland": "terrier lakeland",
    "terrier-norfolk": "terrier norfolk",
    "terrier-norwich": "terrier norwich",
    "terrier-patterdale": "terrier patterdale",
    "terrier-russell": "terrier russell",
    "terrier-scottish": "terrier szkocki",
    "terrier-sealyham": "terrier sealyham",
    "terrier-silky": "terrier silky",
    "terrier-tibetan": "terrier tybetański",
    "terrier-toy": "terrier toy",
    "terrier-westhighland": "terrier westhighland",
    "terrier-wheaten": "terrier wheaten",
    "terrier-yorkshire": "york",
    "vizsla": "wyżeł węgierski",
    "waterdog-spanish": "hiszpański pies dowodny",
    "weimaraner": "wyżeł weimarski krótkowłosy",
    "whippet": "chart angielski",
    "wolfhound-irish": "wilczarz irlandzki"
}
